# Generated by Django 5.2.5 on 2025-08-18 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cor_personalizada',
            field=models.CharField(blank=True, help_text='Cor em formato hex', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_dia_todo',
            field=models.BooleanField(default=False, verbose_name='Evento de dia inteiro'),
        ),
        migrations.AddField(
            model_name='evento',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='privado',
            field=models.BooleanField(default=True, verbose_name='Evento privado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#6366f1', max_length=7)),
                ('icone', models.CharField(default='calendar', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Evento',
                'verbose_name_plural': 'Categorias de Eventos',
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='agenda.categoriaevento'),
        ),
        migrations.CreateModel(
            name='EventoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=10)),
                ('intervalo', models.IntegerField(default=1, help_text='A cada X dias/semanas/meses/anos')),
                ('dias_semana', models.JSONField(blank=True, help_text='Para recorrência semanal', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Para recorrência mensal', null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('max_ocorrencias', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('evento_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencia', to='agenda.evento')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=10)),
                ('tempo_antecedencia', models.IntegerField(help_text='Minutos antes do evento')),
                ('mensagem_customizada', models.TextField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='agenda.evento')),
            ],
            options={
                'verbose_name': 'Notificação de Evento',
                'verbose_name_plural': 'Notificações de Eventos',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('plano', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='free', max_length=20)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('limite_eventos_mes', models.IntegerField(default=10)),
                ('email_verificado', models.BooleanField(default=False)),
                ('token_verificacao', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
